apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kmbdev
namePrefix: kdev-
secretGenerator:
  - literals:
      - password=sa123$DEV
    name: db-sa-password
resources:
  - namespace.yaml
  - ../base
labels:
  - includeSelectors: true
    pairs:
      env: dev
patches:
  - path: basedatos-patch.yaml
  - path: backend-dep-patch.yaml
  - path: backend-lb-patch.yaml
  - path: frontend-patch.yaml
